# Generated by Django 4.2.6 on 2023-10-11 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taskusers.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_postsmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='author',
            field=models.ForeignKey(default=taskusers.tasks.models.get_default_author, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
